# Generated by Django 3.2.6 on 2023-01-02 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tm_backend', '0002_auto_20230102_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_long', models.CharField(blank=True, max_length=250, null=True)),
                ('lat', models.CharField(blank=True, max_length=250, null=True)),
                ('long', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('landmark', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('app_type', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_backend.category')),
                ('district_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_backend.district')),
                ('thana_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_backend.thana')),
                ('union_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_backend.union')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
