# Generated by Django 3.2.6 on 2023-01-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tm_backend', '0005_auto_20230103_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationpicture',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tm_backend.locationpicture'),
        ),
    ]
