# Generated by Django 3.2.6 on 2023-01-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_backend', '0009_auto_20230111_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='locationAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationPicture', models.CharField(blank=True, max_length=150, null=True)),
                ('division_id', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.CharField(blank=True, max_length=150, null=True)),
                ('category_id', models.CharField(blank=True, max_length=150, null=True)),
                ('district_id', models.CharField(blank=True, max_length=150, null=True)),
                ('thana_id', models.CharField(blank=True, max_length=150, null=True)),
                ('union_id', models.CharField(blank=True, max_length=150, null=True)),
                ('lat_long', models.CharField(blank=True, max_length=250, null=True)),
                ('lat', models.CharField(blank=True, max_length=250, null=True)),
                ('long', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('landmark', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('app_type', models.CharField(blank=True, max_length=150, null=True)),
                ('district_name', models.CharField(blank=True, max_length=150, null=True)),
                ('division_name', models.CharField(blank=True, max_length=150, null=True)),
                ('union_name', models.CharField(blank=True, max_length=150, null=True)),
                ('thana_name', models.CharField(blank=True, max_length=150, null=True)),
                ('user_name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'location_all',
                'managed': False,
            },
        ),
    ]
