# Generated by Django 3.2.6 on 2023-01-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tm_backend', '0010_locationall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_backend.category'),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationPicture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tm_backend.locationpicture'),
        ),
        migrations.AlterField(
            model_name='location',
            name='union_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tm_backend.union'),
        ),
    ]
