# Generated by Django 3.2.6 on 2023-02-02 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tm_backend', '0011_auto_20230125_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='location',
            name='app_type',
            field=models.CharField(choices=[('M', 'Mobile'), ('W', 'Web')], default='M', max_length=1),
        ),
        migrations.CreateModel(
            name='AssignTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_start_date', models.DateField()),
                ('task_end_date', models.DateField()),
                ('task_assign', models.CharField(blank=True, max_length=500, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
