# Generated by Django 3.2.6 on 2023-01-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20230102_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='time_intervial',
            field=models.CharField(blank=True, help_text='input in second format', max_length=20, null=True),
        ),
    ]
